//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evente_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija uspješno dodana!.
        /// </summary>
        internal static string add_category_succ {
            get {
                return ResourceManager.GetString("add_category_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad uspješno dodan!.
        /// </summary>
        internal static string add_city_succ {
            get {
                return ResourceManager.GetString("add_city_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država uspješno dodana!.
        /// </summary>
        internal static string add_ctry_succ {
            get {
                return ResourceManager.GetString("add_ctry_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set karata uspješno dodan!.
        /// </summary>
        internal static string add_karte_succ {
            get {
                return ResourceManager.GetString("add_karte_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizator uspješno dodan!.
        /// </summary>
        internal static string add_org_succ {
            get {
                return ResourceManager.GetString("add_org_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa uspješno dodana!.
        /// </summary>
        internal static string add_tclass_succ {
            get {
                return ResourceManager.GetString("add_tclass_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učesnik uspješno dodan!.
        /// </summary>
        internal static string add_uces_succ {
            get {
                return ResourceManager.GetString("add_uces_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik uspješno dodan!.
        /// </summary>
        internal static string add_usr_succ {
            get {
                return ResourceManager.GetString("add_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite pravilnu adresu.
        /// </summary>
        internal static string adr_len {
            get {
                return ResourceManager.GetString("adr_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa je obavezna.
        /// </summary>
        internal static string adr_req {
            get {
                return ResourceManager.GetString("adr_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad je obavezan.
        /// </summary>
        internal static string city_req {
            get {
                return ResourceManager.GetString("city_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drzava je obavezna.
        /// </summary>
        internal static string cntry_req {
            get {
                return ResourceManager.GetString("cntry_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali učešće.
        /// </summary>
        internal static string del_ev_uc_succ {
            get {
                return ResourceManager.GetString("del_ev_uc_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event uspješno obrisan.
        /// </summary>
        internal static string del_eve_succ {
            get {
                return ResourceManager.GetString("del_eve_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali set karata.
        /// </summary>
        internal static string del_tick_succ {
            get {
                return ResourceManager.GetString("del_tick_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik uspješno obrisan.
        /// </summary>
        internal static string del_usr_succ {
            get {
                return ResourceManager.GetString("del_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke eventa.
        /// </summary>
        internal static string edit_eve_succ {
            get {
                return ResourceManager.GetString("edit_eve_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke korisnika.
        /// </summary>
        internal static string edit_usr_succ {
            get {
                return ResourceManager.GetString("edit_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je zauzet.
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite pravilan email.
        /// </summary>
        internal static string email_format {
            get {
                return ResourceManager.GetString("email_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je obavezan.
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event uspješno dodan!.
        /// </summary>
        internal static string evt_add_succ {
            get {
                return ResourceManager.GetString("evt_add_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vas unos je prekratak.
        /// </summary>
        internal static string field_len {
            get {
                return ResourceManager.GetString("field_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje je obavezno.
        /// </summary>
        internal static string field_req {
            get {
                return ResourceManager.GetString("field_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno.
        /// </summary>
        internal static string fname_req {
            get {
                return ResourceManager.GetString("fname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno.
        /// </summary>
        internal static string lname_req {
            get {
                return ResourceManager.GetString("lname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime ili lozinka nisu validni.
        /// </summary>
        internal static string login_err {
            get {
                return ResourceManager.GetString("login_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo odaberite format slike.
        /// </summary>
        internal static string picture_war {
            get {
                return ResourceManager.GetString("picture_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora sadrzavati 4-20 karaktera, najmanje jedno malo, veliko slovo i broj.
        /// </summary>
        internal static string psw_regex {
            get {
                return ResourceManager.GetString("psw_regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezna.
        /// </summary>
        internal static string psw_req {
            get {
                return ResourceManager.GetString("psw_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravite pravilnu selekciju.
        /// </summary>
        internal static string sel_err {
            get {
                return ResourceManager.GetString("sel_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo napravite pravilnu selekciju eventa.
        /// </summary>
        internal static string sel_eve_err {
            get {
                return ResourceManager.GetString("sel_eve_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo napravite pravilnu selekciju korisnika.
        /// </summary>
        internal static string sel_usr_err {
            get {
                return ResourceManager.GetString("sel_usr_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik mora imati ulogu.
        /// </summary>
        internal static string uloge_req {
            get {
                return ResourceManager.GetString("uloge_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime je zauzeto.
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime je prekratko.
        /// </summary>
        internal static string usrn_len {
            get {
                return ResourceManager.GetString("usrn_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo unesite korisnicno ime.
        /// </summary>
        internal static string usrn_req {
            get {
                return ResourceManager.GetString("usrn_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje!.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
