//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_API.Models
{
    using System;
    
    public partial class Eventi_Report
    {
        public string EventNaziv { get; set; }
        public int BrojKarata { get; set; }
        public string KlasaId { get; set; }
        public string OrganizatorNaziv { get; set; }
        public Nullable<System.DateTime> DatumNarudzbe { get; set; }
        public string BrojNarudzbe { get; set; }
        public Nullable<int> Cijena { get; set; }
    }
}
