//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eventi()
        {
            this.EventiUcesnicis = new HashSet<EventiUcesnici>();
            this.Kartes = new HashSet<Karte>();
            this.Ocjenes = new HashSet<Ocjene>();
        }
    
        public int EventId { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public Nullable<int> MinimumGodine { get; set; }
        public string ObjekatOdrzavanja { get; set; }
        public int OrganizatorId { get; set; }
        public int KategorijaId { get; set; }
        public int GradId { get; set; }
        public string Adresa { get; set; }
        public System.DateTime DatumOdrzavanja { get; set; }
        public bool Status { get; set; }
        public byte[] Slika { get; set; }
        public byte[] SlikaThumb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventiUcesnici> EventiUcesnicis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karte> Kartes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocjene> Ocjenes { get; set; }
        public virtual Kategorije Kategorije { get; set; }
        public virtual Organizatori Organizatori { get; set; }
        public virtual Grad Grad { get; set; }
    }
}
