//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventiUcesnici
    {
        public int EventiId { get; set; }
        public int UcesnikId { get; set; }
    
        public virtual Eventi Eventi { get; set; }
        public virtual Ucesnici Ucesnici { get; set; }
    }
}
