//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_API.Models
{
    using System;
    
    public partial class EventiUcesnici_SearchResult
    {
        public int EventiId { get; set; }
        public int UcesnikId { get; set; }
        public string EventNaziv { get; set; }
        public string UcesnikNaziv { get; set; }
    }
}
