//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_API.Models
{
    using System;
    
    public partial class Eventi_Preporuceni
    {
        public string Naziv { get; set; }
        public byte[] SlikaThumb { get; set; }
        public System.DateTime DatumOdrzavanja { get; set; }
        public string Kategorija { get; set; }
        public Nullable<float> ProsjecnaOcjena { get; set; }
    }
}
