//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Karte()
        {
            this.NarudzbaStavkes = new HashSet<NarudzbaStavke>();
        }
    
        public int KarteId { get; set; }
        public int BrojKarata { get; set; }
        public int EventId { get; set; }
        public string KlasaId { get; set; }
        public int Cijena { get; set; }
    
        public virtual Eventi Eventi { get; set; }
        public virtual Klasa Klasa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarudzbaStavke> NarudzbaStavkes { get; set; }
    }
}
