//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_API.Models
{
    using System;
    
    public partial class Karte_KategorijaResult
    {
        public string Klasa { get; set; }
        public int Cijena { get; set; }
        public int BrojKarata { get; set; }
        public int KarteId { get; set; }
        public int EventId { get; set; }
        public string Naziv { get; set; }
    }
}
