//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_API.Models
{
    using System;
    
    public partial class Karte_SearchResult
    {
        public int KarteId { get; set; }
        public string EventNaziv { get; set; }
        public string KlasaNaziv { get; set; }
        public int BrojKarata { get; set; }
        public int Cijena { get; set; }
    }
}
