//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_API.Models
{
    using System;
    
    public partial class Karte_Korisnici_Kupljene
    {
        public string Naziv { get; set; }
        public System.DateTime DatumOdrzavanja { get; set; }
        public string Klasa { get; set; }
        public Nullable<int> Kupljeno { get; set; }
        public byte[] SlikaThumb { get; set; }
    }
}
