//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarudzbaStavke
    {
        public int NarudzbaStavkeId { get; set; }
        public int KarteId { get; set; }
        public int BrojKarata { get; set; }
        public int NarudzbaId { get; set; }
    
        public virtual Karte Karte { get; set; }
        public virtual Narudzbe Narudzbe { get; set; }
    }
}
