//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evente_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocjene
    {
        public int OcjenaId { get; set; }
        public int EventId { get; set; }
        public int KorisnikId { get; set; }
        public System.DateTime Datum { get; set; }
        public int Ocjena { get; set; }
    
        public virtual Eventi Eventi { get; set; }
        public virtual Korisnici Korisnici { get; set; }
    }
}
